#!/usr/bin/env bash
#export PATH=/data/pypi/bin:$PATH
#export PYTHONUSERBASE='/data/pypi'
# pushd python && pip install . --user --verbose && ~/cadelabs/change-workspace-python-user ; popd
# ln -s /data/cache /home/ray/.cache/bazel

# Compile into local pypi, but copy output to /mnt/cluster_storage/pypi for worker nodes.

set -x

ray stop --force

rm -rf /mnt/cluster_storage/pypi.old* &
cp -R /data/pypi /mnt/cluster_storage/pypi.new &
mv /mnt/cluster_storage/pypi /mnt/cluster_storage/pypi.old.$RANDOM &

wait
mv /mnt/cluster_storage/pypi.new /mnt/cluster_storage/pypi
