#!/usr/bin/env bash

drive_name="${1:-/dev/nvme1n1}"
mount_path="${2:-/data}"

set -x

sudo file -s "$drive_name"
sudo apt install xfsprogs -y
sudo mkfs -t xfs "$drive_name"
sudo mkdir "$mount_path"
sudo mount "$drive_name" "$mount_path"
sudo chown -R ray "$mount_path"
