#!/usr/bin/env python3

from anyscale.sdk.anyscale_client.models.create_cluster_environment import (
    CreateClusterEnvironment,
)
from anyscale import AnyscaleSDK

import os

sdk = AnyscaleSDK(auth_token=os.environ.get('ANYSCALE_CLI_TOKEN', None))

create_cluster_environment = CreateClusterEnvironment(
    name="cade-cpu-dev",
    config_json={
        "base_image": "anyscale/ray-ml:2.3.0-py310-cpu",
        "post_build_cmds": [
            "sudo apt-get update -y",
            "sudo apt-get upgrade -y",
            "pip install --upgrade pip",
            #"sudo apt-get install zsh curl silversearcher-ag jq sysstat vim htop clang-format-12 -y"
            "sudo ln -s /usr/bin/clang-format-12 /usr/bin/clang-format",
            "mkdir -p ~/.vim/cade-cluster-env-token",
        ],
        "python": [
            "black==22.10.0", # for ray lint
            "flake8==3.9.1", # for ray lint
            "mypy==0.982", # for ray lint
            "isort==5.10.1", # for ray lint
        ],
        "debian_packages": [
            "zsh",
            "curl",
            "silversearcher-ag",
            "jq",
            "sysstat",
            "vim",
            "htop",
            "clang-format-12",
        ],
    },
)

print('Building cluster environment')
cluster_environment_build = sdk.build_cluster_environment(
    create_cluster_environment=create_cluster_environment
)

print(f"Cluster Environment built successfully: {cluster_environment_build}")
