#!/usr/bin/env bash

ray stop --force
RAY_core_worker_new_path=0 RAY_core_worker_use_old_path=true ray start \
    --head \
    --port=6379 \
    --object-manager-port=8076 \
    --port=9031 \
    --no-monitor 

    #--object-store-memory 78643200
