#!/usr/bin/env bash

path_to_use=$(python3 << 'EOF'
import os
value = os.environ.get('RAY_core_worker_new_path', None)

if value is None:
    raise ValueError('Expected RAY_core_worker_new_path to be defined')
else:
    print(value)
EOF
)

export RAY_core_worker_new_path=$path_to_use

ray stop --force
ray start \
    --head \
    --port=6379 \
    --object-manager-port=8076 \
    --port=9031 \
    --no-monitor \
    --num-cpus 36

./ds_script.py
