#!/usr/bin/env bash
# This script is only necessary if there are worker nodes.
# Compile into local pypi, but copy output to /mnt/cluster_storage/pypi for worker nodes.
# pushd python && pip install . --user --verbose && ~/cadelabs/change-workspace-python-user ; popd

set -x

ray stop --force

rm -rf /mnt/cluster_storage/pypi.old* &
cp -R /data/pypi /mnt/cluster_storage/pypi.new &
mv /mnt/cluster_storage/pypi /mnt/cluster_storage/pypi.old.$RANDOM &

wait
mv /mnt/cluster_storage/pypi.new /mnt/cluster_storage/pypi
