#!/usr/bin/env bash

set -x
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
git clone git@github.com:cadedaniel/ray.git /data/ray
pushd /data/ray
    git remote add upstream git@github.com:ray-project/ray.git
    git remote add chen git@github.com:scv119/ray.git
    git remote add sang git@github.com:rkooo567/ray.git
    git fetch upstream
    git rebase upstream/master
    git fetch chen dl-serve
popd
