#!/usr/bin/env python3

import signal
import functools

def handler(prefix, signum, frame):
    signame = signal.Signals(signum).name
    print('handle', signame, signum, frame)
    
signal.signal(signal.SIGABRT, functools.partial(handler, 'sigint'))

import os
print(os.getpid())

import time
while True:
    time.sleep(1)
