#!/usr/bin/env python3

# Take a list of Python modules to import.
# Spawn N processes.

# Benchmark: spawn N processes with the imports loaded.
# We will measure with forkserver, and with normal start script and import.


import time

class ProcessStarter:
    def start_proc(self):
        raise NotImplementedError

class ForkBasedProcessStarter(ProcessStarter):
    def __init__(self):
        self._forkserver = None
        self._child_pids = []
    
    @property
    def fs(self):
        if self._forkserver is None:
            self._forkserver = Forkserver()
        return self._forkserver

    def start_proc(self):
        child_pid = self.fs.create_proc()
        self._child_pids.append(child_pid)

    def __del__(self):
        import signal
        import os
        for pid in self._child_pids:
            os.kill(pid, signal.SIGTERM)

class Forkserver:
    def __init__(self):
        from multiprocessing import Process, Pipe

        server_pipe, self.pipe = Pipe()

        args = (server_pipe,)
        self._server = Process(target=self._server_func, args=args)
        self._server.start()

    @staticmethod
    def _server_func(pipe):
        import os

        import slow_import

        while True:
            pipe.recv()

            r, w = os.pipe()
            pid = os.fork()

            if pid == 0:
                os.close(r)
                stdout_fd = 1
                os.dup2(w, stdout_fd)

                print('Child process')
                __import__('user_script')

                os._exit(0)
            else:
                wait_for_stream_to_emit_bytes(r, b'Sleeping forever')
                pipe.send(f'done {pid}')

    def create_proc(self):
        self.pipe.send('create')
        output = self.pipe.recv()
        assert 'done' in output, f'got {output}'
        _, child_pid = output.split(' ')

        return int(child_pid)

    def __del__(self):
        self._server.kill()
        self._server.join()

def wait_for_stream_to_emit_bytes(stream, bstr):
    import select
    import os

    proc_is_initialized = False
    data = b''
    while not proc_is_initialized:
        ready, _, _ = select.select([stream], [], [])

        ready_stream = ready[0]
        if isinstance(ready_stream, int):
            data += os.read(ready_stream, 1024)
        else:
            data += ready_stream.read1()

        proc_is_initialized = bstr in data

class SpawnBasedProcessStarter(ProcessStarter):
    def __init__(self):
        self._proc_list = []

    def start_proc(self):
        import subprocess
        proc = subprocess.Popen(
            "./user_script.py",
            stdout=subprocess.PIPE,
        )
        self._proc_list.append(proc)
        wait_for_stream_to_emit_bytes(proc.stdout, b'Sleeping forever.')

    def __del__(self):
        for proc in self._proc_list:
            proc.kill()

def run_test(num_procs_to_start, method='spawn'):
    if method not in ['forkserver', 'spawn']:
        raise ValueError(f'unknown method {method}')

    cls = ForkBasedProcessStarter if method == 'forkserver' else SpawnBasedProcessStarter
    process_starter = cls()

    import time
    start_time = time.time()
    for i in range(num_procs_to_start):
        process_starter.start_proc()

    dur_s = time.time() - start_time
    print(f'Started {num_procs_to_start} processes using {method} method. Duration: {dur_s:.02f}s')

    del process_starter

if __name__ == '__main__':
    num_procs = 10
    run_test(num_procs, 'forkserver')
    run_test(num_procs, 'spawn')
