#!/usr/bin/env bash

aws \
    --region \
    us-west-2 \
    ec2 \
    describe-instances \
    --filters \
    "Name=instance-id,Values=$(./instance_ids)" \
    --query \
    'Reservations[*].Instances[*].[PublicDnsName]' \
    --output \
    text
