#!/usr/bin/env bash

aws \
    ec2 \
    describe-instances \
    --query 'Reservations[*].Instances[*].[InstanceId, Tags[?Key==`Name`], State.Name]' \
    --filters "Name=instance-id,Values=$(./instance_ids)" \
    --o text \
    --region us-west-2
